# Generated by Django 3.1.3 on 2020-11-15 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.sessao', verbose_name='Sessao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='trabalho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.trabalho', verbose_name='Trabalho'),
        ),
        migrations.AlterField(
            model_name='trabalhoautor',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='core.trabalho', verbose_name='Trabalho'),
        ),
    ]
