# Generated by Django 3.1.3 on 2020-11-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201113_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descriçao')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade')),
                ('tipo', models.CharField(choices=[('P', 'Painel'), ('O', 'Oral')], max_length=1, verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('trabalho_id', models.IntegerField(unique=True, verbose_name='TRABALHO_ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('orientador', models.CharField(max_length=254, verbose_name='Orientador')),
                ('modalidade', models.CharField(max_length=254, verbose_name='Modalidade')),
                ('area', models.CharField(max_length=254, verbose_name='Área')),
                ('ano_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ano')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('curso', models.CharField(max_length=254, verbose_name='Curso')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
        ),
    ]
