# Generated by Django 3.1.3 on 2020-11-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliador_sala_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('autor', models.CharField(max_length=254, verbose_name='Autor')),
                ('trabalho_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trabalho')),
            ],
            options={
                'verbose_name': 'Trabalhoautor',
                'verbose_name_plural': 'Trabalhoautores',
            },
        ),
    ]
